export const LOGIN_REQUEST = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR = 'LOGIN_ERROR_USER';
export const SIGNUP_REQUEST = 'SIGNUP_USER';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR = 'SIGNUP_ERROR_USER';
export const LOGOUT_REQUEST = 'LOGOUT_USER';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR = 'LOGOUT_ERROR_USER';

export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS';
export const FETCH_CURRENT_USER_ERROR = 'FETCH_CURRENT_USER_ERROR';
export const FETCH_CURRENT_USER_REQUEST = 'FETCH_CURRENT_USER_REQUEST';

export const FETCH_CREWS_SUCCESS = 'FETCH_CREWS_SUCCESS';
export const FETCH_CREWS_ERROR = 'FETCH_CREWS_ERROR';
export const FETCH_CREWS_REQUEST = 'FETCH_CREWS_REQUEST';

export const FETCH_CREW_SUCCESS = 'FETCH_CREW_SUCCESS';
export const FETCH_CREW_ERROR = 'FETCH_CREW_ERROR';
export const FETCH_CREW_REQUEST = 'FETCH_CREW_REQUEST';

export const FETCH_CREW_MEMBERS_SUCCESS = 'FETCH_CREW_MEMBERS_SUCCESS';
export const FETCH_CREW_MEMBERS_ERROR = 'FETCH_CREW_MEMBERS_ERROR';
export const FETCH_CREW_MEMBERS_REQUEST = 'FETCH_CREW_MEMBERS_REQUEST';

export const FETCH_CREW_PRICE_HISTORY_SUCCESS = 'FETCH_CREW_PRICE_HISTORY_SUCCESS';
export const FETCH_CREW_PRICE_HISTORY_ERROR = 'FETCH_CREW_PRICE_HISTORY_ERROR';
export const FETCH_CREW_PRICE_HISTORY_REQUEST = 'FETCH_CREW_PRICE_HISTORY_REQUEST';

export const FETCH_CONFIG_SUCCESS = 'FETCH_CONFIG_SUCCESS';
export const FETCH_CONFIG_ERROR = 'FETCH_CONFIG_ERROR';
export const FETCH_CONFIG_REQUEST = 'FETCH_CONFIG_REQUEST';

export const FETCH_USER_CREW_MEMBERS_SUCCESS = 'FETCH_USER_CREW_MEMBERS_SUCCESS';
export const FETCH_USER_CREW_MEMBERS_ERROR = 'FETCH_USER_CREW_MEMBERS_ERROR';
export const FETCH_USER_CREW_MEMBERS_REQUEST = 'FETCH_USER_CREW_MEMBERS_REQUEST';

export const FETCH_USER_CREW_RANKING_SUCCESS = 'FETCH_USER_CREW_RANKING_SUCCESS';
export const FETCH_USER_CREW_RANKING_ERROR = 'FETCH_USER_CREW_RANKING_ERROR';
export const FETCH_USER_CREW_RANKING_REQUEST = 'FETCH_USER_CREW_RANKING_REQUEST';

export const SET_BUY_MEMBER = 'SET_BUY_MEMBER';
export const CANCEL_BUY_MEMBER = 'CANCEL_BUY_MEMBER';

export const BUY_ROWER_REQUEST = 'BUY_ROWER_REQUEST';
export const BUY_ROWER_SUCCESS = 'BUY_ROWER_SUCCESS';
export const BUY_ROWER_ERROR = 'BUY_ROWER_ERROR';

export const SELL_ROWER_REQUEST = 'SELL_ROWER_REQUEST';
export const SELL_ROWER_SUCCESS = 'SELL_ROWER_SUCCESS';
export const SELL_ROWER_ERROR = 'SELL_ROWER_ERROR';

export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';

export const UPLOAD_BUMPS_SUCCESS = 'UPLOAD_BUMPS_SUCCESS';
export const UPLOAD_BUMPS_ERROR = 'UPLOAD_BUMPS_ERROR';
export const UPLOAD_BUMPS_REQUEST = 'UPLOAD_BUMPS_REQUEST';

export const FETCH_STATUS_SUCCESS = 'FETCH_STATUS_SUCCESS';
export const FETCH_STATUS_ERROR = 'FETCH_STATUS_ERROR';
export const FETCH_STATUS_REQUEST = 'FETCH_STATUS_REQUEST';

export const UPDATE_STATUS_SUCCESS = 'UPDATE_STATUS_SUCCESS';
export const UPDATE_STATUS_ERROR = 'UPDATE_STATUS_ERROR';
export const UPDATE_STATUS_REQUEST = 'UPDATE_STATUS_REQUEST';
